# Generated by Django 4.2.3 on 2023-07-28 13:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("LITReviews", "0002_ticket_review"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ticket",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="ticket_images"),
        ),
    ]
